sudo: required
dist: trusty

language: cpp

compiler: 
    - clang 
    - gcc

env:
  - CTEST_OUTPUT_ON_FAILURE=1

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
# uncomment for ubuntu precise. not needed for >=trusty - if [ "$CXX" = "g++" ]; then sudo apt-get install -y -qq g++-4.8; export CXX="g++-4.8" CC="gcc-4.8"; else echo "yes" | sudo add-apt-repository 'deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main'; echo "yes" | sudo add-apt-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main'; wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -; sudo apt-get update; sudo apt-get install -qq --allow-unauthenticated llvm-3.6 llvm-3.6-dev clang-3.6 libstdc++-4.8-dev; export CXX="clang++-3.6" CC="clang-3.6"; fi
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y wget
  - sudo apt-get install -y libtool
  - sudo apt-get install -y devscripts # mk-build-deps
# -- get libsml --
  - git clone https://github.com/volkszaehler/libsml.git # or github.com/TheCount/libsml.git # or https://github.com/dailab/libsml.git
  - cd libsml 
  - sudo mk-build-deps --install debian/control
  - debuild -b -us -uc 
  - cd ..  
# -- install libsml --
  - sudo dpkg -i  libsml1*.deb 
# -- get builddependencies 
  - sudo mk-build-deps --install debian/control  
# -- install leptonica --
  - sudo apt-get install -y libpng-dev libtiff-dev
  - wget http://www.leptonica.org/source/leptonica-1.71.tar.gz
  - tar -zxvf leptonica-1.71.tar.gz
  - cd leptonica-1.71
  - ./configure --disable-programs
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
# -- install libmbus --
  - git clone https://github.com/rscada/libmbus
  - cd libmbus
  - ./build.sh
  - sudo make install
  - cd ..
  - sudo apt-get install -y lcov

script:
  - cmake . -DENABLE_OCR=ON -DSML_HOME=/usr/local/src/libsml/sml && make && make test
